name: ibis-dask-dev
channels:
  - conda-forge
dependencies:
    # Hard dependencies
    - multipledispatch>=0.6.0
    - numpy>=1.19
    - pandas>=1.1
    - pytz>=2020.1
    - toolz>=0.10
    - ibis-framework>=1.3.0
    - dask>=2.27.0

    # Dev tools
    - black=19.10b0
    - flake8>=3.8
    - isort>=5.3
    - mypy>=0.782
    - pre-commit>=2.6
    - pydocstyle>=4.0
    - pytest>=5.4
    - pytest-cov>=2.10
    - pytest-mock>=3.1

    - pip
